# Generated by Django 3.0.7 on 2020-06-03 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('balance', models.FloatField(verbose_name='Balance')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_comment', models.TextField(verbose_name='Comment')),
                ('tx_date', models.DateTimeField(verbose_name='Date')),
                ('tx_sum', models.FloatField(verbose_name='Sum')),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txs', to='API.Wallet')),
            ],
        ),
    ]
