# Generated by Django 3.0.7 on 2020-06-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='wallet_id',
            new_name='wallet',
        ),
    ]
