# Generated by Django 3.0.7 on 2020-06-03 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='txs', to='API.Wallet'),
            preserve_default=False,
        ),
    ]
