# Generated by Django 3.0.7 on 2020-06-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_transaction_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance'),
        ),
    ]
